### PR TITLE
Fix NPE for issues #241 and #235

### PR DESCRIPTION
**Pull request by 0x006EA1E5**

### CODE REVIEW

**Comment by 0x006EA1E5** [comment]
Where should I add the tests? regression-lib?  which package?

**Comment by bernhardttom** [comment]
add an RegressionExecution to EventMapCore or EventMapProperties

**Comment by bernhardttom** [comment]
change already merged

**Comment by 0x006EA1E5** [comment]
Do you know when this is planned to be released?

**Comment by bernhardttom** [comment]
the 8.8.0 release is early January 2022

**Pull request closed without merging**
