### PR TITLE
Make ExprConcatNode threadsafe

### PR DESCRIPTION
**Pull request by georgenicoll**
Fix for https://github.com/espertechinc/esper/issues/21

### CODE REVIEW

**Comment by bernhardttom** [comment]
Thanks for the pull request. We will need to rewrite the changes into the code instead of merging the pull request because we don't have a contributor license agreement from you.

**Comment by georgenicoll** [comment]
Ok - if you want me to provide a patch then let me know.

**Comment by georgenicoll** [comment]
Alternatively - if you want a contributor license agreement from me then I can do this.

**Comment by bernhardttom** [comment]
Thanks again, our changes will be merged soon.

**Pull request closed without merging**
