### PR TITLE
fix mapped property argument parsing in PropertyParserNoDep

### LINKED ISSUE #175: SingleRowFunction not resolved with single "." string literal parameter
When I have a single-row function with a single string parameter, the compiler always fails when I try to pass a string literal with a dot in it.

``` java
import com.espertech.esper.common.client.configuration.Configuration;
import com.espertech.esper.compiler.client.CompilerArguments;
import com.espertech.esper.compiler.client.EPCompilerProvider;

public class Main {
    public static void main(String[] args) throws Exception {
        var compiler = EPCompilerProvider.getCompiler();
        var configuration = new Configuration();
        configuration.getCompiler().addPlugInSingleRowFunction("Bar", Main.class.getCanonicalName(), "Bar");
        var arguments = new CompilerArguments(configuration);

        // this works fine
        compiler.compile("create variable Object Foo = Bar(\"test\")", arguments);

        // this doesn't work
        compiler.compile("create variable Object Foo = Bar(\".\")", arguments);
    }

    public static String Bar(String input) {
        return input;
    }
}
```

```
com.espertech.esper.compiler.client.EPCompileException: Failed to validate variable-assignment expression 'Bar(".")': Failed to resolve enumeration method, date-time method or mapped property 'Bar(".")': Failed to resolve '.Bar' to a property, single-row function, aggregation function, script, stream or class name [create variable Object Foo = Bar(".")]
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:150)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compile(CompilerHelperModuleProvider.java:82)
	at com.espertech.esper.compiler.internal.util.EPCompilerImpl.compile(EPCompilerImpl.java:89)
	at Main.main(Main.java:19)
Caused by: com.espertech.esper.compiler.client.EPCompileExceptionItem: Failed to validate variable-assignment expression 'Bar(".")': Failed to resolve enumeration method, date-time method or mapped property 'Bar(".")': Failed to resolve '.Bar' to a property, single-row function, aggregation function, script, stream or class name
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:125)
	... 3 more
Caused by: com.espertech.esper.common.internal.compile.stage2.StatementSpecCompileException: Failed to validate variable-assignment expression 'Bar(".")': Failed to resolve enumeration method, date-time method or mapped property 'Bar(".")': Failed to resolve '.Bar' to a property, single-row function, aggregation function, script, stream or class name
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:278)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:110)
	... 3 more
Caused by: com.espertech.esper.common.internal.epl.expression.core.ExprValidationException: Failed to validate variable-assignment expression 'Bar(".")': Failed to resolve enumeration method, date-time method or mapped property 'Bar(".")': Failed to resolve '.Bar' to a property, single-row function, aggregation function, script, stream or class name
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtree(ExprNodeUtilityValidate.java:137)
	at com.espertech.esper.common.internal.context.aifactory.createvariable.StmtForgeMethodCreateVariable.make(StmtForgeMethodCreateVariable.java:77)
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:214)
	... 4 more
Caused by: com.espertech.esper.common.internal.epl.expression.core.ExprValidationException: Failed to resolve enumeration method, date-time method or mapped property 'Bar(".")': Failed to resolve '.Bar' to a property, single-row function, aggregation function, script, stream or class name
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.resolveStaticMethodOrField(ExprNodeUtilityValidate.java:355)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:254)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtree(ExprNodeUtilityValidate.java:118)
	... 6 more

Process finished with exit code 0
```

### PR DESCRIPTION
**Pull request by icholy**
Fixes #175

The test case I added fails without these changes.

### CODE REVIEW

**Comment by icholy** [comment]
I originally tried to use your `Tokenizer` class, but it doesn't tokenize strings correctly :(

**Comment by icholy** [comment]
@bernhardttom happy new year! Do you think you'll have a chance to review this change any time soon?

**Comment by bernhardttom** [comment]
The changes look good. Do you have an CLA in place for Esper? Since its GPL licensed the project requires a CLA for contributions.

**Comment by icholy** [comment]
@bernhardttom I haven't signed a CLA yet. I looked around the repo/website but didn't find an application form. How do I go about doing that?

**Comment by bernhardttom** [comment]
Hm there doesn't seem to be a link on the site. Here is the direct link http://static.espertech.com/cla/CLA.pdf

**Comment by icholy** [comment]
@bernhardttom the form is out of date. It's not possible to enter the correct year. Also, what email address should I send it to?

**Comment by bernhardttom** [comment]
the form is now updated. Please email to info@espertech.com

**Comment by icholy** [comment]
@bernhardttom I've sent the signed form.

**Comment by bernhardttom** [comment]
ok thank you

**Pull request merged**
